name: Publish
run-name: Publish @sapphire/${{ inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to release
        required: true
        type: choice
        options:
          - api
          - editable-commands
          - hmr
          - i18next
          - logger
          - pattern-commands
          - scheduled-tasks
          - subcommands
          - utilities-store
      skip-automatic-bump:
        description: Whether to skip the automatic bumping of the packageversion
        required: false
        default: false
        type: boolean

jobs:
  PublishPackage:
    name: Publish @sapphire/${{ inputs.package}}
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      project-name: '@sapphire/${{ inputs.package}}'
      working-directory: packages/${{ inputs.package }}
      skip-automatic-bump: ${{ inputs.skip-automatic-bump }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
